name: Abrir iOS Simulator

on:
  workflow_dispatch:

jobs:
  open-ios-simulator:
    runs-on: macos-latest

    steps:
      - name: Confirmar versión de Xcode
        run: xcodebuild -version

      - name: Listar dispositivos disponibles
        run: xcrun simctl list devices available

      - name: Bootear simulador válido
        run: |
          DEVICE_ID=$(xcrun simctl list devices available | grep -E "iPhone [0-9]+" | grep -m1 -oE "[0-9A-F\-]{36}")
          echo "📱 Usando dispositivo $DEVICE_ID"

          xcrun simctl boot "$DEVICE_ID"
          xcrun simctl bootstatus "$DEVICE_ID" -b
          echo "✅ Simulador abierto y listo"

      - name: Tomar screenshot del simulador
        run: |
          mkdir -p artifacts
          xcrun simctl io booted screenshot artifacts/sim.png

      - name: Subir screenshot como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: simulador
          path: artifacts/sim.png

