name: Abrir iOS Simulator

on:
  workflow_dispatch:

jobs:
  open-ios-simulator:
    runs-on: macos-latest

    steps:
      - name: Confirmar versión de Xcode
        run: xcodebuild -version

      - name: Listar dispositivos disponibles
        run: xcrun simctl list devices available

      - name: Bootear primer simulador disponible
        run: |
          DEVICE_ID=$(xcrun simctl list devices available | grep "Shutdown" | head -n 1 | sed -E 's/.*\(([A-F0-9\-]+)\) \(Shutdown\)/\1/')
          echo "📱 Usando dispositivo $DEVICE_ID"

          xcrun simctl boot "$DEVICE_ID"
          xcrun simctl bootstatus "$DEVICE_ID" -b
          echo "✅ Simulador abierto y listo"

      - name: Tomar screenshot del simulador
        run: |
          mkdir -p artifacts
          xcrun simctl io booted screenshot artifacts/sim.png

      - name: Subir screenshot como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: simulador
          path: artifacts/sim.png
