name: Abrir iOS Simulator

on:
  workflow_dispatch:

jobs:
  open-ios-simulator:
    runs-on: macos-latest

    steps:
      - name: Confirmar Xcode activo
        run: xcodebuild -version

      - name: Bootear simulador iPhone 14
        run: |
          DEVICE_ID=$(xcrun simctl list devices available | grep "iPhone 14 (" | head -n 1 | awk '{print $NF}' | tr -d '()')
          echo "📱 Usando dispositivo $DEVICE_ID"
          
          # Bootear simulador
          xcrun simctl boot "$DEVICE_ID" || true

          # Esperar que esté listo
          xcrun simctl bootstatus "$DEVICE_ID" -b
          echo "✅ Simulador abierto y listo"

      - name: Tomar screenshot del simulador
        run: |
          mkdir -p artifacts
          xcrun simctl io booted screenshot artifacts/sim.png

      - name: Subir screenshot como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: simulador
          path: artifacts/sim.png
