name: Abrir iOS Simulator

on:
  workflow_dispatch:

jobs:
  open-ios-simulator:
    runs-on: macos-latest

    steps:
      - name: Seleccionar versión de Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.app
          xcodebuild -version

      - name: Listar dispositivos disponibles
        run: xcrun simctl list devices

      - name: Bootear simulador iPhone 14
        run: |
          DEVICE_ID=$(xcrun simctl list devices | grep "iPhone 14" | grep -v unavailable | head -n 1 | awk '{print $NF}' | tr -d '()')
          echo "📱 Usando dispositivo $DEVICE_ID"
          
          # Bootear
          xcrun simctl boot "$DEVICE_ID"

          # Abrir la app de simulador en background
          open -a Simulator

          # Esperar que esté listo
          xcrun simctl bootstatus "$DEVICE_ID" -b
          echo "✅ Simulador abierto y listo"
